name: UoEx_OceanICU_v2.2
channels:
  - conda-forge
dependencies:
  - python = 3.9
  - pandas
  - geopandas = 0.12.2
  - statsmodels
  - cmocean
  - scipy = 1.10.1
  - pip
  - pip:
    - tensorflow == 2.10.0
    - fluxengine
    - pyco2sys
    - tf2-som
    - scikit-gstat
    - pyshp
